[project]
name = "crewai-agenticai-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[tools]>=1.7.1",
    "litellm>=1.75.3",
    "openai>=1.83.0",
    "python-dotenv>=1.1.1",
]
